In [2]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn import metrics
import seaborn as sns
import matplotlib.pyplot as plt

df = pd.read_csv("Car-dataset.csv")
df.head()

,Name,Min Price (Lakh),Max Price (Lakh),Range (kmpl),CC,Seats,Variants,Type,Ex-Showroom Price,RTO,Insurance,Other,Onroad Price
0,Mahindra Thar,11.35,17.60,15.20,1497,4,19,Petrol,1430000,143000.0,84367.0,14300,"16,71,667"
1,Maruti Swift,6.49,9.60,24.80,1197,5,11,Petrol,649000,46240.0,27791.0,5485,"7,28,516"
2,Mahindra Scorpio,13.62,17.42,22.00,2184,7,4,Diesel,1361600,175000.0,85943.0,27532,"16,50,075"
3,Tata Punch,6.13,10.20,20.09,1199,5,25,Petrol,612900,42903.0,35311.0,0,"6,91,114"
4,Hyundai Creta,11.00,20.15,17.40,1497,5,28,Petrol,1099900,116863.0,45300.0,11599,"12,73,662"

In [3]:
df.shape

(21, 13)

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Name               21 non-null     str
 1   Min Price (Lakh)   21 non-null     float64
 2   Max Price (Lakh)   21 non-null     float64
 3   Range (kmpl)       21 non-null     float64
 4   CC                 21 non-null     int64
 5   Seats              21 non-null     int64
 6   Variants           21 non-null     int64
 7   Type               21 non-null     str
 8   Ex-Showroom Price  21 non-null     int64
 9   RTO                21 non-null     float64
 10  Insurance          21 non-null     float64
 11  Other              21 non-null     int64
 12  Onroad Price       21 non-null     str
dtypes: float64(5), int64(5), str(3)
memory usage: 2.3 KB

In [5]:
df.describe()

,Min Price (Lakh),Max Price (Lakh),Range (kmpl),CC,Seats,Variants,Ex-Showroom Price,RTO,Insurance,Other
count,21.000000,21.000000,21.000000,21.000000,21.000000,21.000000,2.100000e+01,2.100000e+01,21.000000,21.000000
mean,15.129048,42.762857,17.781429,1690.857143,5.571429,22.190476,2.639533e+06,2.894617e+05,116669.697905,25116.952381
std,19.837477,77.051152,3.886819,536.710377,1.075706,21.404717,5.187114e+06,6.419840e+05,205833.811082,52708.566299
min,2.360000,9.600000,9.200000,1197.000000,4.000000,2.000000,6.128000e+05,4.290300e+04,25916.000000,0.000000
25%,7.490000,13.030000,16.000000,1199.000000,5.000000,9.000000,7.515000e+05,5.340500e+04,33850.000000,4500.000000
50%,9.790000,17.420000,17.440000,1497.000000,5.000000,19.000000,1.089900e+06,1.089900e+05,42196.000000,11599.000000
75%,13.850000,26.040000,20.090000,1997.000000,7.000000,26.000000,1.430000e+06,1.750000e+05,85943.000000,17719.000000
max,97.000000,285.000000,24.800000,2997.000000,8.000000,100.000000,2.360000e+07,2.950000e+06,939295.000000,236000.000000

In [6]:
df.isnull().sum()

Name                 0
Min Price (Lakh)     0
Max Price (Lakh)     0
Range (kmpl)         0
CC                   0
Seats                0
Variants             0
Type                 0
Ex-Showroom Price    0
RTO                  0
Insurance            0
Other                0
Onroad Price         0
dtype: int64

In [7]:
df.head(10)

,Name,Min Price (Lakh),Max Price (Lakh),Range (kmpl),CC,Seats,Variants,Type,Ex-Showroom Price,RTO,Insurance,Other,Onroad Price
0,Mahindra Thar,11.35,17.60,15.20,1497,4,19,Petrol,1430000,143000.0,84367.0,14300,"16,71,667"
1,Maruti Swift,6.49,9.60,24.80,1197,5,11,Petrol,649000,46240.0,27791.0,5485,"7,28,516"
2,Mahindra Scorpio,13.62,17.42,22.00,2184,7,4,Diesel,1361600,175000.0,85943.0,27532,"16,50,075"
3,Tata Punch,6.13,10.20,20.09,1199,5,25,Petrol,612900,42903.0,35311.0,0,"6,91,114"
4,Hyundai Creta,11.00,20.15,17.40,1497,5,28,Petrol,1099900,116863.0,45300.0,11599,"12,73,662"
5,Mahindra XUV700,13.99,26.04,15.00,1999,5,49,Petrol,1399000,139900.0,83172.0,13990,"16,36,062"
6,Tata Nexon,8.00,15.80,17.44,1199,5,100,Petrol,799990,55999.0,42196.0,0,"8,98,185"
7,Maruti Brezza,8.34,14.14,17.38,1462,5,15,Petrol,834000,59210.0,33849.0,5485,"9,32,544"
8,Mahindra XUV 3XO,7.49,15.49,18.89,1197,5,25,Petrol,749000,52430.0,40320.0,0,"8,41,750"
9,Toyota Fortuner,33.43,51.44,10.00,2694,7,7,Petrol,3343000,334300.0,166175.0,33830,"38,77,305"

In [8]:
df['Type'].unique()

<StringArray>
['Petrol', 'Diesel ']
Length: 2, dtype: str

In [9]:
df['Type'] = df['Type'].str.strip()
df['Type'].unique()

<StringArray>
['Petrol', 'Diesel']
Length: 2, dtype: str

In [10]:
X = df[['Min Price (Lakh)', 'Max Price (Lakh)', 'Range (kmpl)', 'CC', 'Seats', 'Variants', 'Type']]
y = df['Ex-Showroom Price']

In [11]:
X = pd.get_dummies(X, columns=['Type'], drop_first=True)
X.head()

,Min Price (Lakh),Max Price (Lakh),Range (kmpl),CC,Seats,Variants,Type_Petrol
0,11.35,17.60,15.20,1497,4,19,True
1,6.49,9.60,24.80,1197,5,11,True
2,13.62,17.42,22.00,2184,7,4,False
3,6.13,10.20,20.09,1199,5,25,True
4,11.00,20.15,17.40,1497,5,28,True

In [12]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [17]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
print("R² Score:", r2_score(y_test, y_pred))

R² Score: 0.31742668940841734

In [13]:
model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [14]:
y_pred = model.predict(X_test)
y_pred

array([892956.94941408, 497429.69052305, 163544.66252895, -75521.13605037,
       733400.91963678])

In [15]:
print("Predicted:", y_pred)
print("Actual:", y_test.values)

Predicted: [892956.94941408 497429.69052305 163544.66252895 -75521.13605037
 733400.91963678]
Actual: [1430000  612800  666000  649000  749000]

In [16]:
from sklearn.metrics import r2_score, mean_absolute_error

r2 = r2_score(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)

print("R² Score:", r2)
print("Mean Absolute Error:", mae)

R² Score: -1.281848060721396
Mean Absolute Error: 378997.78278950293